# Generated by Django 5.0 on 2023-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
