# Generated by Django 4.2.7 on 2023-12-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_rename_texto_comentario_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='titulo',
            new_name='texto',
        ),
    ]
