# Generated by Django 5.0 on 2023-12-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_rename_titulo_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/amyt.jpg'),
        ),
    ]
